export const REGISTER= `/register`
export const LOGIN= `/login`
export const VIEW_COUNTRIES ='/view_countries'
export const VIEW_STATES ='/view_states?country_code='
export const VIEW_SUBURBS ='/view_suburbs?state='
export const CREATE_VENUE ='/create_venue'
export const GET_VENUE ='/view_venues'
export const GET_GAMES ='/view_games'
export const GET_GAME ='/view_game'
export const CREATE_GAME ='/create_game'
export const DELETE_GAME ='/delete_game'
export const EDIT_GAME ='/edit_game'
